#!/bin/bash

detectionModel/darknet detector test detectionModel/model/tmax.data detectionModel/model/yolov4_tmax.cfg detectionModel/model/temper_7000.weights result/img/$1 -thresh 0.65 -dont_show ;

cp ./result/label/tmp.txt ./result/integrate/$2 && cp ./result/label/tmp.txt ./result/label/$3 ;
rm ./result/label/tmp.txt ;
cp ./predictions.jpg ./result/integrate/$4 && cp ./predictions.jpg ./result/predict_Img/$5 ;
cp ./result/img/$6 ./result/integrate/$7 ;

exit 0 ;